--- src/Makefile	2017-04-17 01:49:00.061563494 -0400
+++ src/Makefile	2016-10-02 14:51:11.000000000 -0400
@@ -1,4 +1,4 @@
-SUBDIRS=ap common crypto drivers eapol_auth eapol_supp eap_common eap_peer eap_server l2_packet p2p pae radius rsn_supp tls utils wps wpe
+SUBDIRS=ap common crypto drivers eapol_auth eapol_supp eap_common eap_peer eap_server l2_packet p2p pae radius rsn_supp tls utils wps
 SUBDIRS += fst
 
 all:
